export { default as AuthenticationHeader } from './authentication-header/authentication'
export { default as InputAuth } from './authentication-input/authentication-input'
export { default as ButtonAuth } from './authentication-button/authentication-button'
export { default as RegisterForm  } from './authentication-register-form/register-form'
export { default as LoginForm } from './authentication-login-form/authentication-login-form'